Submit Project for review
AyoubMs/catalog_of_my_things_ruby pull request #49
Opened 2022-06-29 21:59 UTC by Ismailco

- [x] Setup linters
- [x] Create README documentation
- [x] Use Gitflow
- [x] Create Item class
- [x] Create item.rb file
- [x] create main.rb
- [x] create app.rb

##### Implement startup actions:
- [x] Present the user with a list of options to perform.
- [x] Let users choose an option.
- [x] If needed, ask for parameters for the option.
- [x] Have a way to quit the app.
- [x] Create can_be_archived?()
- [x] Create move_to_archive()
- [x] Create Book class
- [x] Create a Label class with an association to the Item class (in a separate .rb file).
- [x] All Book class properties visible in the diagram are defined and set up in the constructor method.
- [x] All Label class properties visible in the diagram are defined and set up in the constructor method.
- [x] Implement add_item method in the Label class
   - [x] It takes an instance of the Item class as an input
   - [x] It adds the input item to the collection of items
   - [x] It adds self as a property of the item object
 - [x] Implement can_be_archived?() in the Book class
   - [x] It overrides the method from the parent class
   - [x] It returns true if the parent's method returns true AND if on_spotify equals true. otherwise, it returns false
- [ ] Create Game class
- [ ] Create Author class
- [ ] Implement add_item method in the Author class
- [ ] Implement can_be_archived?() in the Game class
- [x] Create unit test for Book
- [x] Create unit test for can_be_archived? method
- [x] Create unit test for Label
- [x] Create unit test for add_item method
- [x] Created MusicAlbum class in a separate .rb file.
- [x] Created Genre class with an association to the Item class (in a separate .rb file).
- [x] Implemented these methods:
  - [x] add_item method in the Genre class
  - [x] can_be_archived?() in the MusicAlbum class
- [x] Added unit tests for all implemented methods.
- [x] Added the following options in the app file:
  - [x] list_music_albums method
  - [x] list_all_genres method
  - [x] add_music_album method
- [x] All data is preserved in the albums.json file.
- [x] Create schema for the game, music_albums, genres, and author tables in sql/schema.sql
- [x] Create `book_options.rb` with all the options
- [x] Create options for book & label
- [x] Implement the `list_all_books`
- [x] Implement the `list_all_labels`
- [x] Implement `add_book`
- [x] Change app.rb to exit the programe only if the user input 10
- [x] Add the options to app.rb
- [x] Create schema.sql
  - [x] Create books table
  - [x] Create labels table
- [x] Create read_book_data
- [x] Create write_book_data
- [x] Save books to ./storage.books.json
- [x] Add options for games that:
  - [x] List of games
  - [x] List all authors (e.g. 'Stephen King')
  - [x] Add a game
- [x] preserve all data by saving collections in .json files.

2022-06-29 23:00 UTC, Whoistolu requested changes
Hi Team

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 23:00 UTC, Whoistolu commented on README.md
> +
- [ ] [REQUIRED] Well done team 👍🏽 However, it is a requirement to document this project in a video presentation. Ensure the maximum presentation of the video is 5 minutes. Also, ensure that the video contains a clear and objective description of the project. All members of the team should appear in the project and make sure that a highlight about a piece of the code that each student is proud of making is inclussive.

2022-06-29 23:00 UTC, Whoistolu commented on schema.sql
> +)
- [x] [OPTIONAL] Kindly ensure to add the rest of the tables (books, games, authors, and labels) in the `schema.sql` file. This will give a new user an idea of how you have structured your database, and how you have split your tables and columns. Kindly ensure that the tables have columns of foreign keys with the appropriate indexes.

2022-06-29 23:00 UTC, Whoistolu commented on sql/schema.sql
> +);
- Great job implementing the tables and columns here. 👍🏽 Kindly remove the other `schema.sql` files you have here already.

2022-06-30 09:16 UTC, Lordkaito approved these changes
Hi @AyoubMs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 09:29 UTC, merged